config/routes.rb
Rails.application.routes.draw do
  resources :plots
  get 'requirements/new'
  get 'requirements/create'
  root 'home#index'
  resources :flat_rentals
  devise_for :users
  resources :flat_rentals do
    resources :messages, only: [:create, :show]
  end
  
  resources :flat_rentals do
    resources :chatroomes, only: [:create, :show]
  end

  resources :requirements, only: [:new, :create, :show, :index]
  
  resources :flat_rentals do
     get :my_flats 
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/message.rb
class Message < ApplicationRecord
  
    belongs_to :chatroome
    validates :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user! # Ensure the user is logged in


  def create
    @message =  Message.create(content: message, chatroome_id: current_user.s)
    render json: {message: @message , message: "Message sent successfully" }


  end
    
  def show
    # Fetch chat messages for a specific flat_rental
    @flat_rental = FlatRental.find(params[:id])
    @messages = @flat_rental.messages
  end

  
   
    private
    
    def message_params
      params.require(:message).permit(:chatroome_id, :content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
hello
<%= link_to 'massage', new_message_path %>

app/views/messages/new.html.erb
<%= form_with(model: @message, url: messages_path, method: :post) do |form| %>
  <%= form.hidden_field :flat_rental_id %>
  <%= form.hidden_field :receiver_id %>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Send Message", class: "btn btn-primary" %>
  </div>
<% end %>