config/routes.rb
Rails.application.routes.draw do
  resources :plots
  get 'requirements/new'
  get 'requirements/create'
  root 'home#index'
  resources :flat_rentals
  devise_for :users
  resources :flat_rentals do
    resources :messages, only: [:create, :show]
  end
  
  resources :flat_rentals do
    resources :chatroomes, only: [:create, :show]
  end

  resources :requirements, only: [:new, :create, :show, :index]
  
  resources :flat_rentals do
     get :my_flats 
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/plot.rb
class Plot < ApplicationRecord
  validates :property_type, :city, :locality, :address, :road_width, :plot_area, :transaction_type, :property_availability, :expected_price, :price_per_sqyrd, presence: true
  validates :road_width, :plot_area, :expected_price, :price_per_sqyrd, numericality: { greater_than: 0 }

  belongs_to :user
  has_many_attached :images

  PROPERTY_TYPES = ['Residential', 'Commercial']
  PRESENT_IN = [ 'An independent land', 'Present in a society']

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  before_action :set_plot, only: %i[ show edit update destroy ]

  # GET /plots or /plots.json
  def index
    @plots = Plot.all
  end

  # GET /plots/1 or /plots/1.json
  def show
  end

  # GET /plots/new
  def new
    @plot = Plot.new
  end

  # GET /plots/1/edit
  def edit
  end

  # POST /plots or /plots.json
  def create
    @plot = Plot.new(plot_params)
    @plot.user_id = current_user.id
    respond_to do |format|
      if @plot.save
        format.html { redirect_to plot_url(@plot), notice: "Plot was successfully created." }
        format.json { render :show, status: :created, location: @plot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plots/1 or /plots/1.json
  def update
    respond_to do |format|
      if @plot.update(plot_params)
        format.html { redirect_to plot_url(@plot), notice: "Plot was successfully updated." }
        format.json { render :show, status: :ok, location: @plot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plots/1 or /plots/1.json
  def destroy
    @plot.destroy

    respond_to do |format|
      format.html { redirect_to plots_url, notice: "Plot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plot
      @plot = Plot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plot_params
      params.require(:plot).permit(:property_type, :city, :locality, :address, :road_width, :plot_area, :transaction_type, :property_availability, :expected_price, :price_per_sqyrd, :corner_plot, :images)
    end
end

app/helpers/plots_helper.rb
module PlotsHelper
end

app/views/plots/_form.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<%= stylesheet_link_tag "style3.css"%>
<body>

<div id="regForm">
<%= form_with(model: plot) do |form| %>
  <!-- Circles which indicates the steps of the form: -->
  <div style="text-align:center; margin-bottom:30px;">
    <div class="step"><i class="fa-solid fa-landmark ico" style="font-size:35px; margin-top:20%;"></i></div>
    <div class="step"><i class="fa-solid fa-indian-rupee-sign" style="font-size:35px; margin-top:20%;"></i></div>
    <div class="step"><i class="fa-solid fa-image" style="font-size:35px; margin-top:20%;"></i></div>
  </div>
  <!-- One "tab" for each step in the form: -->
  <div class="tab">
    <h3 style="text-align:center; margin-bottom:25px;">Basic details</h3>
    <div class="form-row">
      <div class="form-holder" >
       <%= form.select :property_type, Plot::PROPERTY_TYPES, prompt: 'Select Property Type' , style:"" %>  
      </div>
      <div class="form-holder">
       <label for="posting_type">Property Availability :</label>&nbsp &nbsp
       <%= form.radio_button :property_availability, 'New PropertY' %> New PropertY &nbsp &nbsp
       <%= form.radio_button :property_availability, 'Resale' %> Resale 
      </div>
    </div>
    <div class="form-row">
      <div class="form-holder" >
       <%= form.select :transaction_type , Plot::PRESENT_IN, prompt: 'select present in' %>
      </div>
      <div class="form-holder" >
       <%= form.text_field :address, class: 'form-control' , placeholder:"Enter Address"%>
      </div>
    </div>  
    <div class="form-row"> 
      <div class="form-holder"> 
       <%= form.text_field :city, class: 'form-control' , placeholder:"city" %>
      </div> 
      <div class="form-holder" >
       <%= form.text_field :locality, class: 'form-control' , placeholder:"locality"  %>
      </div>
    </div>  
  </div>
  <div class="tab">
    <h3 style="text-align:center; margin-bottom:25px;">Preference DETAILS</h3>
   <div class="form-row">     
      <div class="form-holder"> 
        <%= form.number_field :road_width, placeholder:"Road width" ,class:"form-control" %>
      </div>
      <div class="form-holder"> 
        <%= form.number_field :plot_area, placeholder:"Plot Area" ,class:"form-control" %>
      </div>
   </div>
    <div class="form-row">     
      <div class="form-holder"> 
        <%= form.text_field :expected_price, placeholder:"Expected Price" ,class:"form-control" %>
      </div>
      <div class="form-holder"> 
        <%= form.text_field :price_per_sqyrd, placeholder:"Price Per Sqyrd" ,class:"form-control" %>
      </div>
    </div>
    <div class="form-row">     
      <div class="form-holder"> 
        <%= form.label :corner_plot%>
        <%= form.check_box :corner_plot %>
      </div>
    </div>
  </div>
  <div class="tab">
    <h3 style="text-align:center; margin-bottom:25px;">Upload Images</h3>
    <div style="display:flex; justify-content: center;">
        <div style="border:dotted 2px; mex-height:400px; width:500px; text-align:center;"> 
            <p>you upload atlist 4 images</p>
            <p><%= form.file_field :images, multiple: true, id:"gallery-photo-add" %></p>
            <div class="gallery"></div>
        </div>        
    </div>
    <div style="text-align:center; margin-top:30px;">       
        <%= form.submit 'Finish', class:"btn"%>                     
    </div>
  </div>
  <div style="overflow:auto;">
    <div style="float:right;">
      <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
      <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
    </div>
  </div>
<% end %>  
</div>
                 
<script>
var currentTab = 0; // Current tab is set to be the first tab (0)
showTab(currentTab); // Display the current tab

function showTab(n) {
  // This function will display the specified tab of the form...
  var x = document.getElementsByClassName("tab");
  x[n].style.display = "block";
  
  if (n == 0) {
    document.getElementById("prevBtn").style.display = "none"; // Hide the "Previous" button on the first step
  } else {
    document.getElementById("prevBtn").style.display = "inline";
  }
  
  if (n == (x.length - 1)) {
    document.getElementById("nextBtn").style.display = "none"; // Hide the "Next" button on the last step
    document.getElementById("prevBtn").style.display = "inline"; // Show the "Previous" button on the last step
    document.getElementById("submitBtn").style.display = "inline"; // Show the "Submit" button on the last step
  } else {
    document.getElementById("nextBtn").style.display = "inline";
    document.getElementById("submitBtn").style.display = "none"; // Hide the "Submit" button for other steps
  }
 
  //... and run a function that will display the correct step indicator:
  fixStepIndicator(n);
}

function nextPrev(n) {
  // This function will figure out which tab to display
  var x = document.getElementsByClassName("tab");
  // Exit the function if any field in the current tab is invalid:
  if (n == 1 && !validateForm()) return false;
  // Hide the current tab:
  x[currentTab].style.display = "none";
  // Increase or decrease the current tab by 1:
  currentTab = currentTab + n;
  // if you have reached the end of the form...
  
  // Otherwise, display the correct tab:
  showTab(currentTab);
}

function validateForm() {
  // This function deals with validation of the form fields
  var x, y, i, valid = true;
  x = document.getElementsByClassName("tab");
  y = x[currentTab].getElementsByTagName("input");
  // A loop that checks every input field in the current tab:
  for (i = 0; i < y.length; i++) {
    // If a field is empty...
    if (y[i].value == "") {
      // add an "invalid" class to the field:
      y[i].className += " invalid";
      // and set the current valid status to false
      valid = false;
    }
  }
  // If the valid status is true, mark the step as finished and valid:
  if (valid) {
    document.getElementsByClassName("step")[currentTab].className += " finish";
  }
  return valid; // return the valid status
}

function fixStepIndicator(n) {
  // This function removes the "active" class of all steps...
  var i, x = document.getElementsByClassName("step");
  for (i = 0; i < x.length; i++) {
    x[i].className = x[i].className.replace(" active", "");
  }
  //... and adds the "active" class on the current step:
  x[n].className += " active";
}
</script>

<script>
    $(function() {
    // Multiple images preview in the browser
    var imagesPreview = function(input, placeToInsertImagePreview) {
        if (input.files) {
            var filesAmount = input.files.length;

            for (i = 0; i < filesAmount; i++) {
                var reader = new FileReader();

                reader.onload = function(event) {
                    // Create an image element
                    var image = $($.parseHTML('<img>')).attr('src', event.target.result);
                    
                    // Set the width of the image (change 100 to your desired width)
                    image.attr('style', 'width: 100px');

                    // Append the image to the container
                    image.appendTo(placeToInsertImagePreview);
                }

                reader.readAsDataURL(input.files[i]);
            }
        }
    };

    $('#gallery-photo-add').on('change', function() {
        imagesPreview(this, 'div.gallery');
    });
});

</script>

</body>
</html>
    

app/views/plots/_plot.html.erb
<div id="<%= dom_id plot %>">
  <p>
    <strong>Property type:</strong>
    <%= plot.property_type %>
  </p>

  <p>
    <strong>City:</strong>
    <%= plot.city %>
  </p>

  <p>
    <strong>Locality:</strong>
    <%= plot.locality %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= plot.address %>
  </p>

  <p>
    <strong>Road width:</strong>
    <%= plot.road_width %>
  </p>

  <p>
    <strong>Plot area:</strong>
    <%= plot.plot_area %>
  </p>

  <p>
    <strong>Transaction type:</strong>
    <%= plot.transaction_type %>
  </p>

  <p>
    <strong>Property availability:</strong>
    <%= plot.property_availability %>
  </p>

  <p>
    <strong>Expected price:</strong>
    <%= plot.expected_price %>
  </p>

  <p>
    <strong>Price per sqyrd:</strong>
    <%= plot.price_per_sqyrd %>
  </p>

  <p>
    <strong>Corner plot:</strong>
    <%= plot.corner_plot %>
  </p>

  <p>
    <strong>Images:</strong>
    <%= plot.images %>
  </p>

</div>

app/views/plots/edit.html.erb
<h1>Editing plot</h1>

<%= render "form", plot: @plot %>

<br>

<div>
  <%= link_to "Show this plot", @plot %> |
  <%= link_to "Back to plots", plots_path %>
</div>

app/views/plots/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Plots</h1>

<div id="plots">
  <% @plots.each do |plot| %>
    <%= render plot %>
    <p>
      <%= link_to "Show this plot", plot %>
    </p>
  <% end %>
</div>

<%= link_to "New plot", new_plot_path %>

app/views/plots/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>FormWizard_v8</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="author" content="colorlib.com">
        <%= stylesheet_link_tag "https://use.fontawesome.com/releases/v5.15.3/css/all.css" %>
        <%= stylesheet_link_tag "style3.css"%>
	</head>
<style>
           
</style>
	<body>
        <div class="page-head"> 
            <div class="container">
                <div class="row">
                    <div class="page-head-content">
                        <h1 class="page-title" style="float:left;">Submit new property</h1>               
                    </div>
                </div>
            </div>
        </div>
        <div class="wizard-header">
            <h3 style="color:gray; text-align:center;">
             <b>Submit</b> YOUR PROPERTY <br>
             <small>Lorem ipsum dolor sit amet, consectetur adipisicing.</small>
            </h3>
        </div>    
<!-- Template created and distributed by Colorlib -->
</body>
</html>
<%= render "form", plot: @plot %>

<br>

<div>
  <%= link_to "Back to plots", plots_path %>
</div>

app/views/plots/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plot %>

<div>
  <%= link_to "Edit this plot", edit_plot_path(@plot) %> |
  <%= link_to "Back to plots", plots_path %>

  <%= button_to "Destroy this plot", @plot, method: :delete %>
</div>