config/routes.rb
Rails.application.routes.draw do
  resources :plots
  get 'requirements/new'
  get 'requirements/create'
  root 'home#index'
  resources :flat_rentals
  devise_for :users
  resources :flat_rentals do
    resources :messages, only: [:create, :show]
  end
  
  resources :flat_rentals do
    resources :chatroomes, only: [:create, :show]
  end

  resources :requirements, only: [:new, :create, :show, :index]
  
  resources :flat_rentals do
     get :my_flats 
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/flat_rental.rb
class FlatRental < ApplicationRecord
    
    validates :property_type, :posting_type, :bedrooms, :furnishing_status, :present_in, :floor_no, :monthly_rent, :security_deposit, presence: true
    validates :bedrooms, :floor_no, :washrooms, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

    PROPERTY_TYPES = ['Residential', 'Commercial']
    FURNISHING_STATUS = ['Furnished', 'Unfurnished', 'Semifurnished']
    PRESENT_IN = ['An independent building', 'An independent flat(s)', 'Present in a society']
    FLOOR_NO = ['1' , '2' , '3' , '4' , '5', '6' ]

    # # serialize :room_facilities, Array
    # # serialize :images, Array
    has_many_attached :images
    validates :country, presence: true
    validates :city, presence: true
    has_many :messages
    has_many :chatroomes
    
    belongs_to :user
    
end

app/controllers/flat_rentals_controller.rb
class FlatRentalsController < ApplicationController
  before_action :set_flat_rental, only: %i[ show edit update destroy ]

  # GET /flat_rentals or /flat_rentals.json
  def index
    # @flat_rentals = FlatRental.select(:property_type, :posting_type)
    @flat_rentals = FlatRental.all
    # render json: @flat_rentals
  end
  
  # GET /flat_rentals/1 or /flat_rentals/1.json
  def show
    @flat_rental = FlatRental.find(params[:id])
    # If you need to include the associated user, you can do:
    @user = @flat_rental.user
    @messages = @flat_rental.messages
    @first_image = @flat_rental.images.first
    @last_image = @flat_rental.images.last
    @second_image = @flat_rental.images.second
    @therid_image = @flat_rental.images.third
  end

  # GET /flat_rentals/new
  def new
    @flat_rental = FlatRental.new
  end
  
  # GET /flat_rentals/1/edit
  def edit
  end

  # POST /flat_rentals or /flat_rentals.json
  def create
    @flat_rental = FlatRental.new(flat_rental_params)
    @flat_rental.user_id = current_user.id
    respond_to do |format|
      if @flat_rental.save
        format.html { redirect_to flat_rental_url(@flat_rental), notice: "Flat rental was successfully created." }
        format.json { render :show, status: :created, location: @flat_rental }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat_rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flat_rentals/1 or /flat_rentals/1.json
  def update
    respond_to do |format|
      if @flat_rental.update(flat_rental_params)
        format.html { redirect_to flat_rental_url(@flat_rental), notice: "Flat rental was successfully updated." }
        format.json { render :show, status: :ok, location: @flat_rental }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat_rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flat_rentals/1 or /flat_rentals/1.json
  def destroy
    @flat_rental.destroy

    respond_to do |format|
      format.html { redirect_to flat_rentals_url, notice: "Flat rental was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def my_flats
    @flats = current_user.flat_rentals
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat_rental
      @flat_rental = FlatRental.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_rental_params
      params.require(:flat_rental).permit(:property_type, :posting_type, :bedrooms, :furnishing_status, :present_in, :floor_no, :monthly_rent, :security_deposit , :washrooms, :preferred_gender, :tenant_preference, :parking_availability, :country, :city, :location , room_facilities: [] , images:[])
    end
end

app/helpers/flat_rentals_helper.rb
module FlatRentalsHelper
end

app/views/flat_rentals/_flat_rental.html.erb
<div id="<%= dom_id flat_rental %>">
  <p>
    <strong>Property type:</strong>
    <%= flat_rental.property_type %>
  </p>

  <p>
    <strong>Posting type:</strong>
    <%= flat_rental.posting_type %>
  </p>

  <p>
    <strong>Bedrooms:</strong>
    <%= flat_rental.bedrooms %>
  </p>

  <p>
    <strong>Furnishing status:</strong>
    <%= flat_rental.furnishing_status %>
  </p>

  <p>
    <strong>Present in:</strong>
    <%= flat_rental.present_in %>
  </p>

  <p>
    <strong>Floor no:</strong>
    <%= flat_rental.floor_no %>
  </p>

  <p>
    <strong>Monthly rent:</strong>
    <%= flat_rental.monthly_rent %>
  </p>

  <p>
    <strong>Security deposit:</strong>
    <%= flat_rental.security_deposit %>
  </p>

  <p>
    <strong>Room facilities:</strong>
    <%= flat_rental.room_facilities %>
  </p>

  <p>
    <strong>Washrooms:</strong>
    <%= flat_rental.washrooms %>
  </p>

  <p>
    <strong>Preferred gender:</strong>
    <%= flat_rental.preferred_gender %>
  </p>

  <p>
    <strong>Tenant preference:</strong>
    <%= flat_rental.tenant_preference %>
  </p>

  <p>
    <strong>Parking availability:</strong>
    <%= flat_rental.parking_availability %>
  </p>

    
</div>

app/views/flat_rentals/_form.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<body>

<div id="regForm">
<%= form_with(model: @flat_rental) do |form| %>
  <!-- Circles which indicates the steps of the form: -->
  <div style="text-align:center; margin-bottom:30px;">
    <div class="step"><i class="fa-solid fa-house ico" style="font-size:35px; margin-top:20%;"></i></div>
    <div class="step"><i class="fa-solid fa-indian-rupee-sign" style="font-size:35px; margin-top:20%;"></i></div>
    <div class="step"><i class="fa-solid fa-inbox" style="font-size:35px; margin-top:20%;"></i></div>
    <div class="step"><i class="fa-solid fa-image" style="font-size:35px; margin-top:20%;"></i></div>
  </div>
  <!-- One "tab" for each step in the form: -->
  <div class="tab">
    <h3 style="text-align:center; margin-bottom:25px;">Basic details</h3>
    <div class="form-row">
      <div class="form-holder" >
       <%= form.select :property_type, FlatRental::PROPERTY_TYPES, prompt: 'Select Property Type' , style:"" %>  
      </div>
      <div class="form-holder">
       <label for="posting_type">Posting Us:</label>&nbsp &nbsp
       <%= form.radio_button :posting_type, 'Full House' %> Full House &nbsp &nbsp
       <%= form.radio_button :posting_type, 'On Sharing' %> On Sharing House 
      </div>
    </div>
    <div class="form-row">
      <div class="form-holder" >
       <%= form.select :present_in , FlatRental::PRESENT_IN, prompt: 'select present in' %>
      </div>
      <div class="form-holder" >
       <%= form.country_select :country, priority: ['India'], class: 'form-control' %>
      </div>
    </div>  
    <div class="form-row"> 
      <div class="form-holder"> 
       <%= form.text_field :city, class: 'form-control' , placeholder:"city" %>
      </div> 
      <div class="form-holder" >
       <%= form.text_field :location, class: 'form-control' , placeholder:"location"  %>
      </div>
    </div>
    <div class="form-row">     
      <div class="form-holder"> 
       <%= form.select :furnishing_status , FlatRental::FURNISHING_STATUS, prompt: 'select furnishing status' %>
     </div>
     <div class="form-holder"> 
     </div>
    </div>   
  </div>
  <div class="tab">
    <h3 style="text-align:center; margin-bottom:25px;">Preference DETAILS</h3>
   <div class="form-row">     
      <div class="form-holder"> 
        <%= form.number_field :bedrooms, placeholder:"No. of Bedrooms" ,class:"form-control" %>
      </div>
      <div class="form-holder"> 
        <%= form.select :floor_no , FlatRental::FLOOR_NO, prompt: 'select Floor NO.' %>
      </div>
   </div>
    <div class="form-row">     
      <div class="form-holder"> 
         <%= form.number_field :washrooms, placeholder:"No. of Washroom" ,class:"form-control" %>
      </div>
      <div class="form-holder"> 
        <label for="posting_type"><b>Preferred Gender :</b></label>&nbsp &nbsp
        <%= form.radio_button :preferred_gender, 'male' %> Male &nbsp &nbsp
        <%= form.radio_button :preferred_gender, 'Femal' %> Femal &nbsp &nbsp
        <%= form.radio_button :preferred_gender, 'Both' %> Both
      </div>
   </div>
    <div class="form-row">     
      <div class="form-holder"> 
        <%= form.text_field :monthly_rent, placeholder:"Monthly Rent" ,class:"form-control" %>
      </div>
      <div class="form-holder"> 
        <label for="posting_type"><b>Tenant Preference :</b></label>&nbsp &nbsp
        <%= form.radio_button :tenant_preference, 'Professionals' %> Professionals &nbsp &nbsp
        <%= form.radio_button :tenant_preference, 'Students' %> Students &nbsp &nbsp
        <%= form.radio_button :tenant_preference, 'Both' %> Both
      </div>
   </div>
    <div class="form-row">     
      <div class="form-holder"> 
        <%= form.text_field :security_deposit, placeholder:"Security Deposit" ,class:"form-control" %>
      </div>
      <div class="form-holder"> 
        <label for="posting_type"><b>Parking Availability :</b></label>&nbsp &nbsp
        <%= form.radio_button :parking_availability, '2-whealer' %> 2-whealer &nbsp &nbsp
        <%= form.radio_button :parking_availability, 'car parking' %> car parking &nbsp &nbsp
        <%= form.radio_button :parking_availability, 'Both' %> Both
      </div>
   </div>     
  </div>
  <div class="tab">
    <h3 style="text-align:center; margin-bottom:25px;">facilities</h3>
    <table>
                    <tr>
                        <td><i class="fa-solid fa-bed sol"></i> &nbsp &nbsp <b class="textface">Bed</b>
                            <%= form.check_box :room_facilities, { multiple: true, class:"facilies" }, 'Bed', nil %>
                         </td>
                        <td><svg xmlns="http://www.w3.org/2000/svg" class="sol" height="1em" viewBox="0 0 576 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M240 144A96 96 0 1 0 48 144a96 96 0 1 0 192 0zm44.4 32C269.9 240.1 212.5 288 144 288C64.5 288 0 223.5 0 144S64.5 0 144 0c68.5 0 125.9 47.9 140.4 112h71.8c8.8-9.8 21.6-16 35.8-16H496c26.5 0 48 21.5 48 48s-21.5 48-48 48H392c-14.2 0-27-6.2-35.8-16H284.4zM144 80a64 64 0 1 1 0 128 64 64 0 1 1 0-128zM400 240c13.3 0 24 10.7 24 24v8h96c13.3 0 24 10.7 24 24s-10.7 24-24 24H280c-13.3 0-24-10.7-24-24s10.7-24 24-24h96v-8c0-13.3 10.7-24 24-24zM288 464V352H512V464c0 26.5-21.5 48-48 48H336c-26.5 0-48-21.5-48-48zM48 320h80 16 32c26.5 0 48 21.5 48 48s-21.5 48-48 48H160c0 17.7-14.3 32-32 32H64c-17.7 0-32-14.3-32-32V336c0-8.8 7.2-16 16-16zm128 64c8.8 0 16-7.2 16-16s-7.2-16-16-16H160v32h16zM24 464H200c13.3 0 24 10.7 24 24s-10.7 24-24 24H24c-13.3 0-24-10.7-24-24s10.7-24 24-24z"/></svg> &nbsp &nbsp <b class="textface">Kichen</b>
                            <%= form.check_box :room_facilities, { multiple: true, class:"facilies" }, 'Kichen', nil  %>
                        </td>
                    </tr>
                    <tr>
                        <td><i class="fa-solid fa-shop sol"></i> &nbsp &nbsp <b class="textface">Side Table</b>
                            <%= form.check_box :room_facilities, { multiple: true, class:"facilies" }, 'Side Table', nil  %>
                        </td>
                        <td><i class="fa-solid fa-table-columns sol"></i> &nbsp &nbsp <b class="textface">Cupboard</b>
                            <%= form.check_box :room_facilities, { multiple: true, class:"facilies" }, 'Cupboard', nil  %>
                        </td>
                    </tr>
                    <tr>
                        <td><i class="fa-solid fa-tv sol"></i> &nbsp &nbsp <b class="textface">TV</b>
                            <%= form.check_box :room_facilities, { multiple: true, class:"facilies" }, 'TV',  nil %>
                        </td>
                        <td><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 640 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#7a7a7a}</style><path d="M256 64H64C28.7 64 0 92.7 0 128V384c0 35.3 28.7 64 64 64H256V64zm32 384H576c35.3 0 64-28.7 64-64V128c0-35.3-28.7-64-64-64H288V448zM64 160c0-17.7 14.3-32 32-32h64c17.7 0 32 14.3 32 32V352c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32V160z"/></svg> &nbsp &nbsp <b class="textface">Mattress</b>
                            <%= form.check_box :room_facilities, { multiple: true, class:"facilies" }, 'Mattress',  nil  %>
                        </td>
                    </tr>
                    <tr>
                        <td><i class="fa-solid fa-fan sol"></i> &nbsp &nbsp <b class="textface">Air Cooler</b>
                            <%= form.check_box :room_facilities, { multiple: true, class:"facilies" }, 'Air Cooler', nil  %>
                        </td>
                        <td><i class="fa-solid fa-wifi sol"></i> &nbsp &nbsp <b class="textface">Wi-Fi</b>
                            <%= form.check_box :room_facilities, { multiple: true, class:"facilies" }, 'Wi-Fi', nil %>                       
                        </td>
                    </tr>
                    </table><br/>
  </div>
  <div class="tab">
    <h3 style="text-align:center; margin-bottom:25px;">Upload Images</h3>
    <div style="display:flex; justify-content: center;">
        <div style="border:dotted 2px; mex-height:400px; width:500px; text-align:center;"> 
            <p>you upload atlist 4 images</p>
            <p><%= form.file_field :images, multiple: true, id:"gallery-photo-add" %></p>
            <div class="gallery"></div>
        </div>        
    </div>
    <div style="text-align:center; margin-top:30px;">       
        <%= form.submit 'Finish', class:"btn"%>                     
    </div>
  </div>
  <div style="overflow:auto;">
    <div style="float:right;">
      <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
      <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
    </div>
  </div>
<% end %>  
</div>
                 
<script>
var currentTab = 0; // Current tab is set to be the first tab (0)
showTab(currentTab); // Display the current tab

function showTab(n) {
  // This function will display the specified tab of the form...
  var x = document.getElementsByClassName("tab");
  x[n].style.display = "block";
  
  if (n == 0) {
    document.getElementById("prevBtn").style.display = "none"; // Hide the "Previous" button on the first step
  } else {
    document.getElementById("prevBtn").style.display = "inline";
  }
  
  if (n == (x.length - 1)) {
    document.getElementById("nextBtn").style.display = "none"; // Hide the "Next" button on the last step
    document.getElementById("prevBtn").style.display = "inline"; // Show the "Previous" button on the last step
    document.getElementById("submitBtn").style.display = "inline"; // Show the "Submit" button on the last step
  } else {
    document.getElementById("nextBtn").style.display = "inline";
    document.getElementById("submitBtn").style.display = "none"; // Hide the "Submit" button for other steps
  }
 
  //... and run a function that will display the correct step indicator:
  fixStepIndicator(n);
}

function nextPrev(n) {
  // This function will figure out which tab to display
  var x = document.getElementsByClassName("tab");
  // Exit the function if any field in the current tab is invalid:
  if (n == 1 && !validateForm()) return false;
  // Hide the current tab:
  x[currentTab].style.display = "none";
  // Increase or decrease the current tab by 1:
  currentTab = currentTab + n;
  // if you have reached the end of the form...
  
  // Otherwise, display the correct tab:
  showTab(currentTab);
}

function validateForm() {
  // This function deals with validation of the form fields
  var x, y, i, valid = true;
  x = document.getElementsByClassName("tab");
  y = x[currentTab].getElementsByTagName("input");
  // A loop that checks every input field in the current tab:
  for (i = 0; i < y.length; i++) {
    // If a field is empty...
    if (y[i].value == "") {
      // add an "invalid" class to the field:
      y[i].className += " invalid";
      // and set the current valid status to false
      valid = false;
    }
  }
  // If the valid status is true, mark the step as finished and valid:
  if (valid) {
    document.getElementsByClassName("step")[currentTab].className += " finish";
  }
  return valid; // return the valid status
}

function fixStepIndicator(n) {
  // This function removes the "active" class of all steps...
  var i, x = document.getElementsByClassName("step");
  for (i = 0; i < x.length; i++) {
    x[i].className = x[i].className.replace(" active", "");
  }
  //... and adds the "active" class on the current step:
  x[n].className += " active";
}
</script>

<script>
    $(function() {
    // Multiple images preview in the browser
    var imagesPreview = function(input, placeToInsertImagePreview) {
        if (input.files) {
            var filesAmount = input.files.length;

            for (i = 0; i < filesAmount; i++) {
                var reader = new FileReader();

                reader.onload = function(event) {
                    // Create an image element
                    var image = $($.parseHTML('<img>')).attr('src', event.target.result);
                    
                    // Set the width of the image (change 100 to your desired width)
                    image.attr('style', 'width: 100px');

                    // Append the image to the container
                    image.appendTo(placeToInsertImagePreview);
                }

                reader.readAsDataURL(input.files[i]);
            }
        }
    };

    $('#gallery-photo-add').on('change', function() {
        imagesPreview(this, 'div.gallery');
    });
});

</script>

</body>
</html>
    

app/views/flat_rentals/edit.html.erb
<h1>Editing flat rental</h1>

<%= render "form", flat_rental: @flat_rental %>

<br>

<div>
  <%= link_to "Show this flat rental", @flat_rental %> |
  <%= link_to "Back to flat rentals", flat_rentals_path %>
</div>

app/views/flat_rentals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flat rentals</h1>

<div id="flat_rentals">
  <% @flat_rentals.each do |flat_rental| %>
    <%= render flat_rental %>
    <p>
      <%= link_to "Show this flat rental", flat_rental %>
    </p>
  <% end %>
</div>

<%= link_to "New flat rental", new_flat_rental_path %>

app/views/flat_rentals/my_flats.html.erb
<!doctype html>
<html lang="en">
  <head>
  	
  </head>
  
  <body>
		
		<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar" class="active">
				<div class="custom-menu">
					<button type="button" id="sidebarCollapse" class="btn btn-primary">
	          <i class="fa fa-bars"></i>
	          <span class="sr-only">Toggle Menu</span>
	        </button>
        </div>
				<div class="p-4">
		  		<h1><a href="index.html" class="logo">Flash</a></h1>
	        <ul class="list-unstyled components mb-5">
	          <li class="active">
	            <a href="#"><span class="fa fa-home mr-3"></span>Flats</a>
	          </li>
	          <li>
	              <a href="#"><span class="fa fa-user mr-3"></span> About</a>
	          </li>
	          <li>
              <a href="#"><span class="fa fa-briefcase mr-3"></span> Portfolio</a>
	          </li>
	          <li>
              <a href="#"><span class="fa fa-sticky-note mr-3"></span> Blog</a>
	          </li>
	          <li>
              <a href="#"><span class="fa fa-paper-plane mr-3"></span> Contact</a>
	          </li>
	        </ul>

	        <div class="mb-5">
						<h3 class="h6 mb-3">Subscribe for newsletter</h3>
						<form action="#" class="subscribe-form">
	            <div class="form-group d-flex">
	            	<div class="icon"><span class="icon-paper-plane"></span></div>
	              <input type="text" class="form-control" placeholder="Enter Email Address">
	            </div>
	          </form>
					</div>

	        <div class="footer">
	        	<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
	        </div>

	      </div>
    	</nav>

        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5 pt-5">
        <h2 class="mb-4">Sidebar #03</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <% @flats.each do |data|%>
            <%= data.city %> 
        <% end %>
      </div>
		</div>
    
   
  </body>
</html>

app/views/flat_rentals/new.html.erb
<%= render "form", flat_rental: @flat_rental %>